# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "air" 

# Site Settings
locale                   : "en-US"
title                    : "MetallerTM's Website"
title_separator          : "|"
subtitle                 : # "Subtitle?" # site tagline that appears below site title in masthead
name                     : "Francesco Bruno"
description              : "My personal website to show who I am and what I do."
url                      : "https://metallertm.github.io"
baseurl                  : "/"
repository               : "MetallerTM/MetallerTM.github.io"
# Default image that loads when the primary source cannot be loaded for whatever reason
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : #/assets/images/naologo.webp
masthead_title           : 
words_per_minute         : 200
reCaptcha:
  enabled                : true
  siteKey                : # "6LcvdI0sAAAAACU-FRT8Wj6R86gcjL1IQShUycp3"
  secret                 : # "6LcvdI0sAAAAADrdKY1vFEa6G9qR4iP5hcx7QYFR"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)

social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Francesco Bruno"
  avatar           : "assets/images/naologo.webp"
  bio              : "Spectroscopist and Data Analyst\nSoftware developer"
  location         : "Florence, Italy"
  email            : "bruno@cerm.unifi.it"
  # fediverse      : "@you@instance.social"  # used for fediverse:creator meta tag
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=zeFe_0IAAAAJ&hl=it"
    - label: "ORCID"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0000-0002-4590-4316"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MetallerTM"
    - label: "PyPI"
      icon: "fas fa-fw fa-cube"
      url: "https://pypi.org/user/MetallerTM/"
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-square-facebook"
      # url: "https://facebook.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MetallerTM"
  since: "2026"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Pagination with jekyll-paginate
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#   for configuration details
pagination:
  # Set enabled to true to use paginate v2
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# timezone
timezone: Europe/Rome

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# show_taxonomy: false  # set to false to hide tag/category lists on posts
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  softwares:
    output: true
    permalink: /softwares/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _softwares
  - scope:
      path: ""
      type: softwares
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "sw"



